/*
 * This source file was generated by the Gradle 'init' task
 */
package org.learn.java;

import static org.learn.java.patterns.singleton.SingletonUtils.executeForSynchronisedSingleton;

public class App {
    public static void main(String[] args) {
        executeForSynchronisedSingleton(1000, 4);
    }


}
