/*
 * This source file was generated by the Gradle 'init' task
 */
package org.learn.java;

import org.learn.java.patterns.abstractfactory.AbstractFactoryUtils;

public class App {
    public static void main(String[] args) {
        AbstractFactoryUtils.createWinApplication();
        AbstractFactoryUtils.createMacApplication();
    }


}
