/*
 * This source file was generated by the Gradle 'init' task
 */
package org.learn.java;

import org.learn.java.patterns.factorymethod.FactoryMethodUtils;

import static org.learn.java.patterns.singleton.SingletonUtils.executeForSynchronisedSingleton;

public class App {
    public static void main(String[] args) {
        FactoryMethodUtils.createWindowDialog("windows");
        FactoryMethodUtils.createWindowDialog("html");
    }


}
